config/routes.rb
Ponzi::Application.routes.draw do
  devise_for :housemates
  

  
  resources :charge_transactions

  root :to => "main#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ponzi</title>
  <%= stylesheet_link_tag "ponzi.css" %>
  <% if Rollbar.configuration.enabled -%>
    <%= javascript_include_tag 'rollbar.js' %>
  <% end -%>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  
  <% for name in [:notice, :warning, :message] %>
  	<% if flash[name] %>
  		<%= "<div id=\"#{name}\">#{flash[name]}</div>" %>
  	<% end %>
  <% end %>
  
  <div id="sidebar">
      <h1><%= link_to "Ponzi", :controller => "main", :action => "index" %></h1>
      <div id="authbox">
        <% if housemate_signed_in? -%>
            <%= image_tag('user.png') %>
            <%= current_housemate.name %>
            <br/>
            <%= link_to "Log out", destroy_housemate_session_path %>
        <% else -%>
            <%= link_to "Log in", new_housemate_session_path %>
        <% end -%>
      </div>

      <% if housemate_signed_in? -%>
          <div id="chorebox">
              <h2>Chores</h2>
              <ul>
                  <% @current_chores.each do |chore| %>
                      <li>
                          <b><%= chore.name%></b>
                          <%= frequencyize chore.frequency_amount %> a
                          <%= chore.frequency_unit %>
                      </li>
                  <% end -%>
              </ul>
          </div>
          <div id="financebox">
              <h2>Finance</h2>
              <b>Balance:</b> <%= display_balance current_housemate.balance %>
          </div>
      <% end -%>
  </div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div style="clear: both;"></div>

  <%= yield %>

</body>
</html>